// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlbumsController from "./albums_controller"
application.register("albums", AlbumsController)

import ArtistsController from "./artists_controller"
application.register("artists", ArtistsController)

import Mp3PlayController from "./mp3_play_controller"
application.register("mp3-play", Mp3PlayController)

import Mp3sController from "./mp3s_controller"
application.register("mp3s", Mp3sController)

import PlaylistsPlayController from "./playlists_play_controller"
application.register("playlists-play", PlaylistsPlayController)

import PlaylistsPlayerController from "./playlists_player_controller"
application.register("playlists-player", PlaylistsPlayerController)
